# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='I am default value'),
        ),
    ]
